name: Tests

# bpo-40548: "paths-ignore" is not used to skip documentation-only PRs, because
# it prevents to mark a job as mandatory. A PR cannot be merged if a job is
# mandatory but not scheduled because of "paths-ignore".
on:
  push:
    branches:
    - 3.7-updated
    - custom
    - dev
  pull_request:
    branches:
    - 3.7-updated
    - custom

jobs:
  check_generated_files:
    name: 'Check if generated files are up to date'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: sudo ./.github/workflows/posix-deps-apt.sh
      - name: Build CPython
        run: |
          ./configure --with-pydebug
          make -j4 regen-all
      - name: Check for changes
        run: |
          changes=$(git status --porcelain)
          # Check for changes in regenerated files
          if ! test -z "$changes"
          then
            echo "Generated files not up to date. Perhaps you forgot to run make regen-all ;)"
            echo "$changes"
            exit 1
          fi
      - name: Check exported libpython symbols
        run: make smelly

  build_win32:
    name: 'Windows (x86)'
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - name: Build CPython
      run: .\PCbuild\build.bat -e -p Win32
    - name: Display build info
      run: .\python.bat -m test.pythoninfo
    - name: Tests
      run: .\PCbuild\rt.bat -p Win32 -q -uall -u-cpu -rwW --slowest --timeout=1200 -j0

  build_win_amd64:
    name: 'Windows (x64)'
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - name: Build CPython
      run: .\PCbuild\build.bat -e -p x64
    - name: Display build info
      run: .\python.bat -m test.pythoninfo
    - name: Tests
      run: .\PCbuild\rt.bat -p x64 -q -uall -u-cpu -rwW --slowest --timeout=1200 -j0

  build_macos:
    name: 'macOS'
    runs-on: macos-13
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    steps:
    - uses: actions/checkout@v4
    - name: Install Homebrew dependencies
      run: brew install openssl@3.0 tcl-tk
    - name: Configure CPython
      run: |
        SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk \
        CC=clang \
        CPPFLAGS="-I$(brew --prefix gdbm)/include -I$(brew --prefix xz)/include" \
        LDFLAGS="-L$(brew --prefix gdbm)/lib -L$(brew --prefix xz)/lib" \
        ./configure --prefix=/opt/python-dev \
            --with-pydebug \
            --with-openssl="$(brew --prefix openssl@3.0)" \
            --with-tcltk-libs="$(pkg-config --libs tk)" \
            --with-tcltk-includes="$(pkg-config --cflags tk)"
    - name: Build CPython
      run: make -j4
    - name: Display build info
      run: make pythoninfo
    - name: Tests
      run: make buildbottest TESTOPTS="-j4 -uall,-cpu"

  build_ubuntu_2204:
    name: 'Ubuntu 22.04'
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo ./.github/workflows/posix-deps-apt.sh
    - name: Configure CPython
      run: ./configure --with-pydebug
    - name: Build CPython
      run: make -j4
    - name: Display build info
      run: make pythoninfo
    - name: Tests
      run: xvfb-run make buildbottest TESTOPTS="-j4 -uall,-cpu"
